/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const LayoutDatatable002LazyImport = createFileRoute('/_layout/datatable002')()
const LayoutDatatable001LazyImport = createFileRoute('/_layout/datatable001')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LayoutDatatable002LazyRoute = LayoutDatatable002LazyImport.update({
  path: '/datatable002',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/datatable002.lazy').then((d) => d.Route),
)

const LayoutDatatable001LazyRoute = LayoutDatatable001LazyImport.update({
  path: '/datatable001',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/datatable001.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/datatable001': {
      preLoaderRoute: typeof LayoutDatatable001LazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/datatable002': {
      preLoaderRoute: typeof LayoutDatatable002LazyImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    LayoutDatatable001LazyRoute,
    LayoutDatatable002LazyRoute,
  ]),
])

/* prettier-ignore-end */
